src/Entity/Personnes.php
<?php

namespace App\Entity;

use App\Repository\PersonnesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=PersonnesRepository::class)
 * @UniqueEntity("nom")
 *
 */
class Personnes implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sexe;

    /**
     * @ORM\ManyToOne(targetEntity=Adresses::class, inversedBy="personnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\ManyToMany(targetEntity=Cadeaux::class, inversedBy="personnes")
     */
    private $cadeaux;

    /**
     * @ORM\Column(type="date")
     */
    private $naissance;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    public function __construct()
    {
        $this->cadeaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getAdresse(): ?Adresses
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresses $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Cadeaux[]
     */
    public function getCadeaux(): Collection
    {
        return $this->cadeaux;
    }

    public function addCadeaux(Cadeaux $cadeaux): self
    {
        if (!$this->cadeaux->contains($cadeaux)) {
            $this->cadeaux[] = $cadeaux;
        }

        return $this;
    }

    public function removeCadeaux(Cadeaux $cadeaux): self
    {
        $this->cadeaux->removeElement($cadeaux);

        return $this;
    }

    public function getNaissance(): ?\DateTimeInterface
    {
        return $this->naissance;
    }

    public function setNaissance(\DateTimeInterface $naissance): self
    {
        $this->naissance = $naissance;

        return $this;
    }
    //nouvelle adresse n'existe pas dans la classe Personnes mais on la rajouter dans PersonnesType comme un sous formulaire
    // ce qui introduit l'erreur lors de la creation de l'objet personnes aprtir de ($formAdresse->submit($data)) dans notre controlleur
    //l'ajout de cette methode est pour surmanter l'erreur sans aucun autre effet
    public function getNouvelleAdresse(){
        return $this->getAdresse();
    }
    public function getAge(){
        //$naissanceObj = new \DateTime($this->naissance->format('d-m-Y'));
        $now = new \DateTime();
        $age = $now->diff($this->naissance)->y;
        return $age;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }
    public function getPassword()
    {
        return (string) $this->password;
    }
    public function setPassword($password)
    {
        return $this->password = $password;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->nom;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\Adresses;
use App\Entity\Personnes;
use App\Form\PersonnesAdressesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\User;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
    /**
     * @Route("/inscription/enregistrer", name="inscription")
     */
    public function addInscription(Request $request, UserPasswordEncoderInterface $encoder, ValidatorInterface $validator)
    {
        $data = $this->getJson($request);
        if($data["password"] != $data["password2"]){
            return $this->json(['error' => "La confirmation de mot de passe n'est pas correcte"], 500);
        }

        $em = $this->getDoctrine()->getManager();
        $adresse = $this->getDoctrine()->getRepository(Adresses::class)->findOneBy([
            'ville' => strtoupper($data["ville"]),
            'nomRue' => strtoupper($data["nomRue"]),
            'numRue' => $data["numRue"],
            'codePostal' => $data["codePostal"],
            ]);
        $naissance = \DateTime::createFromFormat("d/m/Y", $data["naissance"]);
        $user = new Personnes();
        $user
            ->setNaissance($naissance)
            ->setNom($data["nom"])
            ->setSexe($data["sexe"])
            ->setRoles(["ROLE_SOUHAIT"])
            ->setPassword($encoder->encodePassword($user,$data["password"]));

        if($adresse == null){
            $adresse = new Adresses();
            $adresse->setNomRue($data["nomRue"])
                ->setNumRue($data["numRue"])
                ->setVille($data["ville"])
                ->setCodePostal($data["codePostal"]);
            $em->persist($adresse);
        }
        $user->setAdresse($adresse);

        if(count($validator->validate($adresse)) >0){
            return $this->json(['fail' => "Données de la adresse invalid"],422 );
        }
        if(count($validator->validate($user)) >0){
            return $this->json(['fail' => "Données invalid"],422 );
        }
        $em->persist($user);
        $em->flush();
        $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
        $this->container->get('security.token_storage')->setToken($token);
        $this->container->get('session')->set('_security_main', serialize($token));
        return $this->json(["success" => "you are connected"]);

    }
    /**
     * @Route("/inscription", name="inscription_page")
     */
    public function inscription()
    {
        $formPersonne = $this->createForm(PersonnesAdressesType::class);
        return $this->render('security/inscription.html.twig',[
            'formPersonne' => $formPersonne->createView()] );
    }
    /**
     * @param Request $request
     * @return mixed
     */
    private function getJson(Request $request)
    {

        $data = json_decode($request->getContent(), true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new HttpException(400, 'Invalid json');
        }
        return $data;
    }
}

templates/security/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des Personnes{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/inscription.css') }}">
{% endblock %}
{% block body %}
    {% block navBar %}
        {% endblock %}
    <div class="containerCnx">
        <div class="leftPart">
            <button class="btn-rond"><img src="{{ asset('img/icon/left.png') }}" alt=""></button>
        </div>
        <div class="containerFormCnx">
            <div class="headerCnx">
                <img src="{{ asset('img/icon2.png') }}" alt="" id="logoSimple">
                <h1 class="titreCnx">S'inscrire</h1>
            </div>
            <div class="contantFormCnx">
                <!-- Formulaire d'ajout -->
                {{ form_start(formPersonne,{'attr': {'id': 'inscription', 'class': 'login-form'}}) }}

                <div  class="alert alert-danger" id="error" style="display: none">
                </div>
                {{ form_row(formPersonne.nom) }}
                {{ form_row(formPersonne.sexe) }}
                {{ form_row(formPersonne.naissance) }}
                {{ form_row(formPersonne.nouvelleAdresse) }}
                <div class="adresse" style="display: none;">
                    {{ form_row(formPersonne.adresse) }}
                </div>
                <label for="first-mdp" >Mot de passe</label>
                <input type="password" id="first-mdp" name="password" class="form-control">

                <label for="second-mdp">Confirmer mot de passe</label>
                <input type="password" id="second-mdp" name="password2" class="form-control">
                <button id="ajoutButton" type="submit" class="btn btn-lg btn-primary" >S'inscrire</button>
                <!--  Formulaire d'ajout -->
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            $('.js-datepicker').datepicker({
                format : 'dd/mm/yyyy',
                daysMin:["Dim","Lun","Mar","Mer","Jeu","Ven","Sam"],
                months:["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]
            });
        });
        //Return le nom des input de symfony sous la forme de cet exemple (adresse[nom] => nom)
        function getNameInput(inputName) {
            let t = inputName.split("");
            let prefix = '';
            for (i = 0; i < t.length; i++) {
                if(t[i] != "[" && t[i] != "]"){
                    prefix += t[i];
                } else if(t[i] == "["){
                    prefix = '';
                }
            }
            return prefix;
        }
        $('#inscription').on('submit', function (e) {
            e.preventDefault();

            var data = {};
            console.log($(this).serializeArray());
            //[ {name: nom-de-input, value: valeur-input}, {...}, {...}, {...}... ]
            $(this).serializeArray().forEach(obj=>{
                let name = getNameInput(obj.name);
                let value = obj.value || '';
                if (data[name]) {
                    if (!Array.isArray(data[name])) {
                        data[name] = [data[name]];
                    }
                    data[name].push(value);
                } else {
                    data[name] = value;
                }
            });
            if(data["password"] == data['password2']){
                $.ajax({
                    url: "/inscription/enregistrer",
                    type: 'POST',
                    dataType: 'json',
                    async: true,
                    data: JSON.stringify(data),

                    success: function (response) {

                        $('#error').css('display', 'none');
                        window.location.replace("{{ absolute_url(path('souhait')) }}");
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log(xhr.responseJSON["fail"]);
                    }
                });
            } else {

                $('#error').css('display', 'block');
                $("#error").html('La confirmation de mot de passe n\'est pas correcte');
            }
            console.log(data);

        });
        $('.btn-rond').on('click', function (e) {
            e.preventDefault();
            window.location.replace("{{ absolute_url(path('app_login')) }}");
        });
    </script>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("/css/indexStyle.css") }}">
    <style>
        body{
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block body %}
    {% block navBar %}
    {% endblock %}
    <div class="indexContent">
        <div class="description">
            <div id="description-content">
                <div>
                    <h1>C'est Noel !</h1>
                </div>
            </div>
        </div>
        <form method="post" class="login-form">
            {% if error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            <h1 class="h3 mb-3 font-weight-normal">Se connecter</h1>
            <label for="inputNom">Nom</label>
            <input type="text" value="{{ last_username }}" name="nom" id="inputNom" class="form-control" required autofocus>
            <label for="inputPassword">Password</label>
            <input type="password" name="password" id="inputPassword" class="form-control" required>

            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

            <button class="btn btn-lg btn-primary" type="submit">
                Se connecter
            </button>
            <a id="inscritptionLink" href="{{ path('inscription_page') }}">S'inscrire</a>
        </form>

    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        //Design Switch form
        $('#switchFormInscription').on('click', function (e) {
            e.preventDefault();
            window.location.replace("{{ absolute_url(path('inscription_page')) }}");
        });
        //Design Switch form

       //Return le nom des input de symfony sous la forme de cet exemple (adresse[nom] => nom)
        $(document).ready(function () {
            $('.js-datepicker').datepicker({
                format : 'dd/mm/yyyy',
                daysMin:["Dim","Lun","Mar","Mer","Jeu","Ven","Sam"],
                months:["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]
            });
        });

    </script>
{% endblock %}